Account:
  connection: doctrine
  tableName: account
  actAs:
    Timestampable:
      updated: { disabled: true }
  options:
    symfony: {filter: false, collate: utf8_unicode_ci, charset: utf8}
  columns:
    id: { type: integer(4), unsigned: true, primary: true, autoincrement: true }
    email: { type: string(255), notnull: true }
    slug: { type: string(255), notnull: true }
    salt: { type: string(255), notnull: true }
    password: { type: string(255), notnull: true }
    state: { type: string(255), notnull: true }
    last_login: { type: timestamp(25) }
    validation_code: { type: string(45) }
    culture: { type: string(3), notnull: true }
    currency: { type: string(3), notnull: true }
    type: { type: string(255), notnull: true }
    is_designer: { type: boolean, default: '0' }
  relations:
    Frapp: { local: id, foreign: creator_id, type: many }
    ProfileCompany: { local: id, foreign: account_id, type: one, cascade: [delete] }
    ProfilePerson: { local: id, foreign: account_id, type: one, cascade: [delete] }
    ProfileOrganization: { local: id, foreign: account_id, type: one, cascade: [delete] }
    
AccountForgotPassword:
  connection: doctrine
  tableName: account_forgot_password
  actAs:
    Timestampable: ~
  options:
    symfony: {filter: false, collate: utf8_unicode_ci, charset: utf8}
  columns:
    account_id: { type: integer(4), unsigned: true, notnull: true }
    unique_key: { type: string(255), primary: true }
    expires_at: { type: timestamp(25), notnull: true }
  relations:
    Account: { local: account_id, foreign: id, type: one, onDelete: CASCADE }

AccountRememberKey:
  connection: doctrine
  tableName: account_remember_key
  actAs:
    Timestampable: ~
  options:
    symfony: {filter: false, collate: utf8_unicode_ci, charset: utf8}
  columns:
    account_id: { type: integer(4), unsigned: true, notnull: true }
    remember_key: { type: string(32), primary: true }
    ip_address: { type: string(50) }
  relations:
    Account: { local: account_id, foreign: id, type: one, onDelete: CASCADE }
      
Location:
  connection: doctrine
  tableName: location
  options:
    symfony: {filter: false, collate: utf8_unicode_ci, charset: utf8}
  columns:
    id: { type: integer(4), unsigned: true, primary: true, autoincrement: true }
    city: { type: string(100), notnull: true }
    region: { type: string(100), notnull: true }
    country: { type: string(2), notnull: true }
    lang: { type: string(2), notnull: true }
    population: { type: integer(3), unsigned: true, default: '0', notnull: true }


ProfileCompany:
  connection: doctrine
  tableName: profile_company
  options:
    symfony: {filter: false, collate: utf8_unicode_ci, charset: utf8}
  columns:
    account_id: { type: integer(4), unsigned: true, primary: true, notnull: true }
    name: { type: string(100), notnull: true }
    brand_name: { type: string(100), notnull: true }
    slogan: { type: string(250) }
    cui: { type: string(100), notnull: true }
    contact_name: { type: string(100) } 
    contact_job_title: { type: string(100) }
    contact_email: { type: string(100) }
    contact_phone: { type: string(100) }
    location_id: { type: integer(4), unsigned: true }
  relations:
    Location: { local: location_id, foreign: id, type: one }
    Account: { local: account_id, foreign: id, type: one }

      
ProfileOrganization:
  connection: doctrine
  tableName: profile_organization
  options:
    symfony: {filter: false, collate: utf8_unicode_ci, charset: utf8}
  columns:
    account_id: { type: integer(4), unsigned: true, primary: true, notnull: true }
    name: { type: string(100), notnull: true }
    brand_name: { type: string(100), notnull: true }
    slogan: { type: string(250) }
    cui: { type: string(100), notnull: true }
    contact_name: { type: string(100) }
    contact_job_title: { type: string(100) }
    contact_email: { type: string(100) }
    contact_phone: { type: string(100) }
    location_id: { type: integer(4), unsigned: true }
  relations:
    Location: { local: location_id, foreign: id, type: one }
    Account: { local: account_id, foreign: id, type: one }


ProfilePerson:
  connection: doctrine
  tableName: profile_person
  options:
    symfony: {filter: false, collate: utf8_unicode_ci, charset: utf8}
  columns:
    account_id: { type: integer(4), unsigned: true, primary: true, notnull: true }
    first_name: { type: string(100) }
    last_name: { type: string(100) }
    slogan: { type: string(250) }
    date_of_birth: { type: date(25) }
    gender: { type: enum, values: ['0', '1'] }
    location_id: { type: integer(4), unsigned: true }
  relations:
    Location: { local: location_id, foreign: id, type: one }
    Account: { local: account_id, foreign: id, type: one }


Session:
  connection: doctrine
  tableName: session
  options:
    symfony: {filter: false, form: false, model: false, collate: utf8_unicode_ci, charset: utf8}
  columns:
    sess_id: { type: string(255), primary: true }
    sess_data: { type: text }
    sess_time: { type: integer(4), unsigned: true, notnull: true }