<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProfilePerson', 'doctrine');

/**
 * BaseProfilePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $account_id
 * @property string $first_name
 * @property string $last_name
 * @property string $slogan
 * @property date $date_of_birth
 * @property enum $gender
 * @property integer $location_id
 * @property Location $Location
 * @property Account $Account
 * 
 * @method integer       getAccountId()     Returns the current record's "account_id" value
 * @method string        getFirstName()     Returns the current record's "first_name" value
 * @method string        getLastName()      Returns the current record's "last_name" value
 * @method string        getSlogan()        Returns the current record's "slogan" value
 * @method date          getDateOfBirth()   Returns the current record's "date_of_birth" value
 * @method enum          getGender()        Returns the current record's "gender" value
 * @method integer       getLocationId()    Returns the current record's "location_id" value
 * @method Location      getLocation()      Returns the current record's "Location" value
 * @method Account       getAccount()       Returns the current record's "Account" value
 * @method ProfilePerson setAccountId()     Sets the current record's "account_id" value
 * @method ProfilePerson setFirstName()     Sets the current record's "first_name" value
 * @method ProfilePerson setLastName()      Sets the current record's "last_name" value
 * @method ProfilePerson setSlogan()        Sets the current record's "slogan" value
 * @method ProfilePerson setDateOfBirth()   Sets the current record's "date_of_birth" value
 * @method ProfilePerson setGender()        Sets the current record's "gender" value
 * @method ProfilePerson setLocationId()    Sets the current record's "location_id" value
 * @method ProfilePerson setLocation()      Sets the current record's "Location" value
 * @method ProfilePerson setAccount()       Sets the current record's "Account" value
 * 
 * @package    newe
 * @subpackage model
 * @author     Iulian Manea <iulian.manea@impurelabs.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProfilePerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_person');
        $this->hasColumn('account_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('first_name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('last_name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('slogan', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('date_of_birth', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('gender', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '0',
              1 => '1',
             ),
             ));
        $this->hasColumn('location_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 4,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Location', array(
             'local' => 'location_id',
             'foreign' => 'id'));

        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id'));
    }
}