<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AccountRememberKey', 'doctrine');

/**
 * BaseAccountRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $account_id
 * @property string $remember_key
 * @property string $ip_address
 * @property Account $Account
 * 
 * @method integer            getAccountId()    Returns the current record's "account_id" value
 * @method string             getRememberKey()  Returns the current record's "remember_key" value
 * @method string             getIpAddress()    Returns the current record's "ip_address" value
 * @method Account            getAccount()      Returns the current record's "Account" value
 * @method AccountRememberKey setAccountId()    Sets the current record's "account_id" value
 * @method AccountRememberKey setRememberKey()  Sets the current record's "remember_key" value
 * @method AccountRememberKey setIpAddress()    Sets the current record's "ip_address" value
 * @method AccountRememberKey setAccount()      Sets the current record's "Account" value
 * 
 * @package    newe
 * @subpackage model
 * @author     Iulian Manea <iulian.manea@impurelabs.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAccountRememberKey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account_remember_key');
        $this->hasColumn('account_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('remember_key', 'string', 32, array(
             'type' => 'string',
             'primary' => true,
             'length' => 32,
             ));
        $this->hasColumn('ip_address', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}