<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Session', 'doctrine');

/**
 * BaseSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sess_id
 * @property text $sess_data
 * @property integer $sess_time
 * 
 * @method string  getSessId()    Returns the current record's "sess_id" value
 * @method text    getSessData()  Returns the current record's "sess_data" value
 * @method integer getSessTime()  Returns the current record's "sess_time" value
 * @method Session setSessId()    Sets the current record's "sess_id" value
 * @method Session setSessData()  Sets the current record's "sess_data" value
 * @method Session setSessTime()  Sets the current record's "sess_time" value
 * 
 * @package    newe
 * @subpackage model
 * @author     Iulian Manea <iulian.manea@impurelabs.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSession extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('sess_id', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('sess_data', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('sess_time', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}