<?php

/**
 * Account
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    newe
 * @subpackage model
 * @author     Iulian Manea <iulian.manea@impurelabs.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Account extends BaseAccount
{
	const TYPE_PERSON       = 0;
	const TYPE_COMPANY      = 1;
	const TYPE_ORGANIZATION = 2;
	
	const STATE_UNCONFIRMED = 0;
	const STATE_ACTIVE      = 1;
	const STATE_PENDING     = 2;
	const STATE_BANNED      = 3;
	const STATE_INACTIVE    = 4;
	const STATE_DESTROYED   = 5;

	public function setValidationCode()
	{
		$code = md5(rand(0, 100000));
		return $this->_set('validation_code', $code);
	}

	public function setPassword($password)
	{
		if (!$password && 0 == strlen($password))
		{
			throw new InvalidArgumentException(sprintf('No password was passed to the setPassword method in class %s', get_class($this)));
		}

		if (!$salt = $this->getSalt()){
			$salt = md5(rand(100000, 999999).$this->getEmail());
			$this->setSalt($salt);
		}

		return $this->_set('password', sha1($salt.$password));
	}

	/**
	 * Returns whether or not the given password is valid.
	 *
	 * @param string $password
	 * @return boolean
	 */
	public function checkPassword($password)
	{
		return $this->getPassword() == sha1($this->getSalt().$password);
	}

	public function resetPassword()
	{
		$newPassword = substr(md5($this->getPassword() . time()), 0, 6);
		$this->setPassword($newPassword);

		return $newPassword;
	}
}