<?php

/**
 * AccountForgotPasswordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountForgotPasswordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountForgotPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountForgotPassword');
    }
}