<?php

/**
 * FrappTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrappTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return FrappTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Frapp');
    }

	/**
	 * Returns the Frapp object that will be put in the sfContext for the loaded frapp.
	 * The basic related objects are preloaded.
	 *
	 * @return Frapp
	 */
	public function getForSetupFilter($slug = null)
	{
		if (!isset($slug)){
			return false;
		}

		return Doctrine_Query::create()
			->from('Frapp f')
			->where('f.slug = ?', $slug)
			->execute();
	}
}