<?php

/**
 * FrappSkinTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrappSkinTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrappSkinTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrappSkin');
    }
}