<?php

/**
 * FrappMdlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrappMdlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrappMdlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrappMdl');
    }
}