<?php

/**
 * Frapp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    newe
 * @subpackage model
 * @author     Iulian Manea <iulian.manea@impurelabs.com>
 */
class Frapp extends BaseFrapp
{
	const STATE_PENDING     = 0;
	const STATE_ACTIVE      = 1;
	const STATE_SUSPICIOUS  = 2;
	const STATE_CLOSED      = 3;
	const STATE_DESTROYED   = 4;

	/**
	 * Returns an array with all the data that should be available in all the views + layout.
	 * 
	 * @return array
	 */
	public function getLayoutDetails()
	{
		return array(
			'id' => $this->getId(),
			'name' => $this->getName(),
			'slogan' => $this->getSlogan(),
			'filename' => $this->getFilename(),
			'state_support_sponsor' => $this->getStateSupportSponsor(),
			'state_support_campaign' => $this->getStateSupportCampaign(),
			'state_support_promote' => $this->getStateSupportPromote(),
			'state_support_petition' => $this->getStateSupportPetition(),
			'menu_item' => array(
				$this->getMenuForView()
			)
		);
	}

	/**
	 * Returns an array with all the elements in the menu
	 */
	public function getMenuForView()
	{

	}
}