<?php

/**
 * Frapp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    newe
 * @subpackage model
 * @author     Iulian Manea <iulian.manea@impurelabs.com>
 */
class Frapp extends BaseFrapp
{
	const STATE_PENDING     = 0;
	const STATE_ACTIVE      = 1;
	const STATE_SUSPICIOUS  = 2;
	const STATE_CLOSED      = 3;
	const STATE_DESTROYED   = 4;

	/**
	 * A collection of FrappMld objects associated with this frapp, ordered by position.
	 * @var Dotrine_Collection
	 */
	protected $mdls = null;

	/**
	 * Returns an array with all the data that should be available in all the views + layout.
	 * 
	 * @return array
	 * @todo
	 */
	public function getLayoutDetails()
	{
		return array(
			'id' => $this->getId(),
			'name' => $this->getName(),
			'slogan' => $this->getSlogan(),
			'filename' => $this->getFilename(),
			'state_support_sponsor' => $this->getStateSupportSponsor(),
			'state_support_campaign' => $this->getStateSupportCampaign(),
			'state_support_promote' => $this->getStateSupportPromote(),
			'state_support_petition' => $this->getStateSupportPetition(),
			'menu_items' => array(
				$this->getMenuForView()
			)
		);
	}

	/**
	 * Returns an array with all the elements in the menu
	 */
	public function getMenuForView()
	{
		$items = array();
		foreach ($this->getMdls() as $mdl){
			$items[] = array(
				'name' => $mdl->getName(),
				'url' => sfContext::getInstance()->getController()->genUrl('@frapp_mdl_' . $mdl->getTypeKey() . '_' . $mdl->getSlug() . '_index?frapp_slug=' . $this->getSlug())
			);
		}

		return $items;
	}

	public function loadMdlRoutes(neweFrappPatternRouting $routing)
	{
		foreach ($this->getMdls() as $mdl){
			$mdlSlug = $mdl->getSlug();
			include sfConfig::get('sf_app_config_dir') . DIRECTORY_SEPARATOR . 'routing_mdl_' . $mdl->getTypeKey() . '.php';
		}
	}
}