<?php

/**
 * ProfileCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileCompanyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileCompany');
    }
}