<?php

/**
 * ProfilePersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfilePersonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfilePersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfilePerson');
    }
}