<?php

/**
 * ProfileOrganization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    newe
 * @subpackage model
 * @author     Iulian Manea <iulian.manea@impurelabs.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class ProfileOrganization extends BaseProfileOrganization
{

}