<?php

/**
 * ProfileOrganizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileOrganizationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileOrganizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileOrganization');
    }
}