<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
	/**
	 * Returns an instance of this class.
	 *
	 *  @return object sfGuardUserTable
	 */
	
	public static function getInstance()
	{
		return Doctrine_Core::getTable('sfGuardUser');
	}
	
	public function getFiltered($filters, $limit= null)
	{
		$q = Doctrine_Query::create()
			->from('sfGuardUser u')
			->leftJoin('u.Permissions p')
			->orderBy('u.id ASC');
			
		if(isset($limit)){
			$q->limit($limit);
		}

		if (isset($filters['id']) && !empty($filters['id'])){
			$q->addWhere('u.id = ?', $filters['id']);
		}
		
		if (isset($filters['name']) && !empty($filters['name'])){
			$q->addWhere('u.first_name REGEXP ? OR u.last_name REGEXP ?', array('(^| |-)' . $filters['name'], '(^| |-)' . $filters['name']));
		}
		
		if (isset($filters['email']) && !empty($filters['email'])){
			$q->addWhere('u.email_address REGEXP ?', '(^| |-)' . $filters['email']);
		}
		
		if (isset($filters['username']) && !empty($filters['username'])){
			$q->addWhere('u.username REGEXP ?', '(^| |-)' . $filters['username']);
		}
		
		if (isset($filters['offset'])){
			$q->offset($filters['offset']);
		}
		
		if (isset($filters['inactive']) && $filters['inactive']){
			if (isset($filters['active']) && $filters['active']){
				$q->addWhere('u.is_active = 0 OR u.is_active = 1');
			} else {
				$q->addWhere('u.is_active = 0');
			}
		}
		
		if (isset($filters['active']) && $filters['active']){
			if (isset($filters['inactive']) && $filters['inactive']){
				$q->addWhere('u.is_active = 1 OR u.is_active = 0');
			} else {
				$q->addWhere('u.is_active = 1');
			}
		}
		
		if (isset($filters['inactive']) && $filters['inactive']){
			if (isset($filters['active']) && $filters['active']){
				$q->addWhere('u.is_active = 0 OR u.is_active = 1');
			} else {
				$q->addWhere('u.is_active = 0');
			}
		}

		$users = $q->execute();
	
		if (isset($filters['webeditors']) && !isset($filters['clients'])){
			foreach ($users as $key => $user){
				if(!$user->hasPermission('Webeditor')){
						unset($users[$key]);
				}
			}
		}
	
		if (isset($filters['clients']) && !isset($filters['webeditors'])){
			foreach ($users as $key => $user){
				if($user->hasPermission('Webeditor')){
						unset($users[$key]);
				}
			}
		}

		
		
		return $users;
	}
	
public function countFiltered($filters)
	{
		$q = Doctrine_Query::create()
			->from('sfGuardUser u')
			->innerJoin('u.Permissions p')
			->orderBy('u.id ASC');

		if (isset($filters['id']) && !empty($filters['id'])){
			$q->addWhere('u.id = ?', $filters['id']);
		}
		
		if (isset($filters['name']) && !empty($filters['name'])){
			$q->addWhere('u.first_name REGEXP ? OR u.last_name REGEXP ?', array('(^| |-)' . $filters['name'], '(^| |-)' . $filters['name']));
		}
		
		if (isset($filters['email']) && !empty($filters['email'])){
			$q->addWhere('u.email_address REGEXP ?', '(^| |-)' . $filters['email']);
		}
		
		if (isset($filters['username']) && !empty($filters['username'])){
			$q->addWhere('u.username REGEXP ?', '(^| |-)' . $filters['username']);
		}
		
		if (isset($filters['offset'])){
			$q->offset($filters['offset']);
		}
		
		if (isset($filters['inactive']) && $filters['inactive']){
			if (isset($filters['active']) && $filters['active']){
				$q->addWhere('u.is_active = 0 OR u.is_active = 1');
			} else {
				$q->addWhere('u.is_active = 0');
			}
		}
		
		if (isset($filters['active']) && $filters['active']){
			if (isset($filters['inactive']) && $filters['inactive']){
				$q->addWhere('u.is_active = 1 OR u.is_active = 0');
			} else {
				$q->addWhere('u.is_active = 1');
			}
		}
		
		if (isset($filters['inactive']) && $filters['inactive']){
			if (isset($filters['active']) && $filters['active']){
				$q->addWhere('u.is_active = 0 OR u.is_active = 1');
			} else {
				$q->addWhere('u.is_active = 0');
			}
		}
		
		$users = $q->execute();
	
		if (isset($filters['webeditors']) && !isset($filters['clients'])){
			foreach ($users as $key => $user){
				if(!$user->hasPermission('Webeditor')){
						unset($users[$key]);
				}
			}
		}
	
		if (isset($filters['clients']) && !isset($filters['webeditors'])){
			foreach ($users as $key => $user){
				if($user->hasPermission('Webeditor')){
						unset($users[$key]);
				}
			}
		}
		
		return $users->count();
	}

	public function getAdminsForWidget()
	{
		$bruteAdmins = Doctrine_Query::create()
			->from('sfGuardUser u')
			->innerJoin('u.Permissions p')
			->where('u.is_active = 1')
			->orderBy('u.id ASC')
			->execute();
		
		$admins = array('' => '');
		foreach ($bruteAdmins as $bruteAdmin){
			$admins[$bruteAdmin->getId()] = $bruteAdmin->getName();
		}
		
		return $admins;
	}

	public function getForApi($term)
	{
		$term = '(^| |-)' . $term ;

		$bruteUsers = Doctrine_Query::create()
			->from('sfGuardUser u')
			->andWhere('u.username REGEXP ?', $term)
			->orderBy('u.username ASC')
			->limit(50)
			->execute();

		$users = array();
		foreach ($bruteUsers as $key => $bruteUser){
			$users[$key]['value'] = $bruteUser->getId();
			$users[$key]['label'] = $bruteUser->getUsername();
		}

		return $users;
	}
}